# Site settings
title: retention
email: contact@brunorl.com
description: clog (code log)
baseurl: "/log"
# url: ""
twitter_username: brunorl_
avatar: "https://pbs.twimg.com/profile_images/504866001742094338/bXvG5z0s.jpeg" # Set footer avatar
paginate: 13

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "b" # Set default author name
      categories: "stuff"
      layout: "post"
      comments: false
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
